language: go
go:
    - 1.3

cache:
  directories:
  - go
  - libmemcached-1.0.18

before_install:
    - sudo apt-get update
    - sudo apt-get install -y automake

install:
    - make memcached
    - make

script:
    - make simplepush
