language: go
go:
- 1.3
install:
- make memcached
- make
script:
- make simplepush
before_deploy:
- mkdir -p build
- gzip simplepush
- cp simplepush.gz build/simplepush.$TRAVIS_OS_NAME.$TRAVIS_COMMIT.gz
deploy:
  provider: s3
  access_key_id: AKIAJPJ3YT7MAF55UGDA
  secret_access_key:
    secure: Iyc3eLG0H/pFot1eNdsgulF0A8SB2ih4gc+FjhxQNE/cOX5Vy7r0ARNkUHLkqi/HkUkP2Dz27OqTmhpcRQ/71rQp/k9IXJaB3EF3VNDnNo7vw6S+wIXG19a0KQC9YGsjDWvCefFkKvOlkviHU/eS7p09Q2dRMNUNL5jUKd/SoKM=
  bucket: travis-binary-uploading
  skip_cleanup: true
  local-dir: build
  on:
    all_branches: true
